// Traduction à l'affichage des textes enregistrés dans l'état (journal chaîné, alertes,
// données de démonstration). Les textes stockés restent en français : les empreintes
// du journal ne changent pas, seule la présentation suit la langue choisie.
import { curLang } from './lang.js';

const ORD = { premier: 'first', second: 'second', deuxième: 'second', troisième: 'third' };

const EXACT = {
  'Système': 'System', 'Automate': 'Automated', 'Détection': 'Detection', 'Assistance': 'Support', 'Opérateur': 'Operator', 'Opératrice': 'Operator',
  'Électeur': 'Voter', 'Administrateur': 'Administrator', 'Bureau de vote': 'Polling station', 'Détenteur de clé': 'Key holder', 'Double signature': 'Dual signature',
  'Présidente': 'Chair', 'Président': 'Chair', 'Expert indépendant': 'Independent expert', 'Organisateur': 'Organiser', 'Organisatrice': 'Organiser', 'Participant': 'Participant',
  'Portail électeur': 'Voter portal', 'nouvelle': 'new', 'traitée': 'handled', 'acquittée': 'acknowledged', 'haute': 'high', 'moyenne': 'medium',
  'Force brute': 'Brute force', 'Géolocalisation inhabituelle': 'Unusual location', 'Réémission d’identifiants': 'Credentials reissued', 'Usurpation suspectée': 'Suspected impersonation',
  'Envoyé': 'Sent', 'Distribué': 'Delivered', 'Majeur': 'Major', 'Mineur': 'Minor', 'Résolu': 'Resolved', 'En cours': 'In progress', 'Remplacée': 'Superseded',
  'Définitive (double signature)': 'Final (dual signature)', 'Contrôlé': 'Checked', 'Validé (double signature)': 'Approved (dual signature)', 'Remis': 'Delivered', 'Plateforme': 'Platform',
  'Procuration': 'Proxy', 'Excusé·e': 'Excused', 'Non arrivé·e': 'Not arrived', 'Salle': 'In the room', 'Visioconférence': 'Video', 'Adopté': 'Adopted', 'Rejeté': 'Rejected',
  'Abonnement semestriel': 'Six-month subscription', 'Jusqu’à 500 participants simultanés': 'Up to 500 concurrent participants', 'Union européenne': 'European Union',
  'Courrier non reçu (NPAI)': 'Letter not received (returned)', 'Mot de passe perdu': 'Password lost', 'Perte du courrier': 'Letter lost', 'Courrier postal': 'Post',
  'Recette avant scrutin': 'Pre-election acceptance test', 'Hybride': 'Hybrid', 'Présentiel': 'In person', 'Bureau de la direction générale': 'Executive office',
  'Direction': 'Management', 'Direction des soins': 'Nursing management', 'Direction générale': 'General management', 'Direction du GIP': 'GIP management',
  'Établissement de santé': 'Healthcare facility', 'Groupement d’intérêt public': 'Public interest group',
  'Collège 1 · Professeurs des universités-praticiens hospitaliers': 'College 1 · University professors and hospital practitioners',
  'Collège 2 · Maîtres de conférences-praticiens hospitaliers': 'College 2 · Associate professors and hospital practitioners',
  'Collège 3 · Praticiens hospitaliers': 'College 3 · Hospital practitioners',
  'Collège 4 · Praticiens contractuels et associés': 'College 4 · Contract and associate practitioners',
  'Collège 5 · Personnels enseignants et hospitaliers non titulaires (CCA, AHU)': 'College 5 · Non-tenured teaching hospital staff (CCA, AHU)',
  'Collège 6 · Sages-femmes': 'College 6 · Midwives',
  'Collège 7 · Pharmaciens, biologistes et odontologistes': 'College 7 · Pharmacists, biologists and dentists',
  'Sages-femmes': 'Midwives', 'Contractuels': 'Contract', 'Pharm./bio./odonto.': 'Pharm./bio./dent.',
  'Connexion à la console d’administration': 'Signed in to the admin console', 'Clé FIDO2': 'FIDO2 key', 'SSO établissement': 'Hospital SSO', 'Code à usage unique': 'One-time code',
  'Brouillon (scrutin futur)': 'Draft (future election)', 'Bloquant': 'Critical',
  'Test de bascule à la demande (démonstration)': 'On-demand failover test (demo)', 'Vote test complémentaire (démonstration)': 'Additional test vote (demo)',
  'Incident déclaré depuis la console (démonstration)': 'Incident reported from the console (demo)',
  'Mise à jour de version. Le vote reste possible grâce à la bascule automatique.': 'Version update. Voting stays available through automatic failover.',
  'Export complet en formats ouverts (réversibilité)': 'Full export in open formats (reversibility)', 'JSON, CSV et XML': 'JSON, CSV and XML',
  'Export CSV (réversibilité)': 'CSV export (reversibility)', 'Urnes et participation': 'Ballot boxes and turnout',
  'Ajournement de la séance faute de quorum': 'Meeting adjourned (no quorum)', 'Nouvelle convocation à prévoir': 'New invitation needed', 'Rupture de quorum': 'Quorum lost',
  'Annulé par l’organisateur': 'Cancelled by the organiser', 'Parapheur électronique': 'E-signature workflow', 'GED de l’établissement': 'Document management',
  'Publication sur le site internet': 'Website publication', '@CTES (collectivités : contrôle de légalité)': '@CTES (legality check)',
  'Bac à sable (aucune donnée réelle)': 'Sandbox (no real data)', 'Membre volontaire (séance de test)': 'Volunteer member (test meeting)',
  'Membre volontaire (session de test)': 'Volunteer member (test session)', 'Session de test': 'Test session', 'Directoire': 'Executive board',
  'Connexion à l’espace du bureau de vote': 'Signed in to the polling station area', 'Clé de sécurité FIDO2': 'FIDO2 security key', 'Carte CPS': 'CPS card',
  'Connexion en lecture seule à l’espace d’expertise': 'Read-only sign-in to the audit area', 'Vérification des scellés et du journal': 'Seals and log checked',
  'Conformes': 'Compliant', 'Écart détecté': 'Mismatch detected', 'Vérification des scellés': 'Seals checked', 'Empreintes conformes': 'Fingerprints match',
  'Cérémonie des clés rejouée (environnement de démonstration)': 'Key ceremony replayed (demo environment)', 'Simulation sans effet sur les urnes en production': 'Simulation, production boxes unaffected',
  'Export de la liste d’émargement': 'Voter roll exported', 'Contrôle déclenché par le bureau': 'Check run by the polling station', 'Procédure d’incident': 'Incident procedure',
  'Les autres urnes restent ouvertes.': 'Other ballot boxes stay open.', 'Après clôture, plus aucun bulletin ne peut être déposé.': 'After closing, no more ballots can be cast.',
  'Attaque par dictionnaire': 'Dictionary attack',
  'Tentatives répétées depuis une même adresse sur 12 identifiants différents. Adresse bloquée automatiquement ; aucun compte compromis.': 'Repeated attempts from one address on 12 different identifiers. Address blocked automatically; no account compromised.',
  'Scrutin plurinominal, second tour à la majorité relative': 'Multi-seat vote, second round by relative majority', 'Élections à la CME 2026': '2026 CME elections',
  'tentatives répétées (force brute)': 'repeated attempts (brute force)', 'connexion depuis une localisation inhabituelle': 'sign-in from an unusual location',
  'Tentatives répétées d’accès participant': 'Repeated participant sign-in attempts', 'Administratrice': 'Administrator',
  'Identité vérifiée · identifiant par courriel, mot de passe par SMS · anciens identifiants révoqués': 'Identity verified · ID by email, password by SMS · old credentials revoked',
  'CSIRMT · salle B': 'CSIRMT · room B', 'Identifiants non reçus': 'Credentials not received', 'Identifiants perdus': 'Credentials lost', 'Compte verrouillé': 'Account locked', 'Assistance (démo)': 'Support (demo)', 'Motion préalable': 'Preliminary motion', 'Amendement': 'Amendment', 'Sous-amendement': 'Sub-amendment',
  'Vote sur l’ensemble': 'Final vote', 'Sondage': 'Poll', 'Vote groupé': 'Grouped vote', 'Procès-verbal': 'Minutes', 'Annexe': 'Appendix',
  'Rapport de présentation': 'Report', 'Projet de délibération': 'Draft resolution', 'Note': 'Note',
};

// Paramètres de sécurité journalisés sous la forme « libellé : valeur »
const SEC = { 'Seuil de verrouillage': 'Lockout threshold', 'Durée de verrouillage': 'Lockout duration', 'Contrôle de géolocalisation': 'Location check', 'Détection d’usurpation': 'Impersonation detection', 'Alertes SMS au bureau': 'SMS alerts to polling station', 'Alertes courriel au bureau': 'Email alerts to polling station' };
const secVal = (v) => v.replace(/^(\d+) essais?$/, '$1 attempts').replace(/^(\d+) min(utes)?$/, '$1 min').replace(/^(?:activée?s?)$/, 'on').replace(/^(?:désactivée?s?)$/, 'off');

// Expressions complètes (premier motif reconnu)
const RX = [
  [/^Création du scrutin « (.*) »$/, 'Create election “$1”'],
  [new RegExp('^(' + Object.keys(SEC).join('|') + ') : (.+)$'), (m, k, v) => SEC[k] + ': ' + secVal(v)],
  [/^(\d+) échecs consécutifs sur l’identifiant (\S+)\. Compte verrouillé (\d+) minutes(?:, déblocage par l’assistance après vérification d’identité)?\.$/, '$1 consecutive failures on identifier $2. Account locked for $3 minutes.'],
  [/^Identifiant (\S+) verrouillé (\d+) min · bureau alerté(?: en temps réel)?$/, 'Identifier $1 locked for $2 min · polling station alerted'],
  [/^Demande en ligne après vérification d’identité\. (.+)\. Anciens identifiants révoqués\.$/, (m, c) => 'Online request after identity check. ' + tx(c) + '. Old credentials revoked.'],
  [/^Électeur (.*)$/, 'Voter $1'],
  [/^Urne (\S+) · (.+) · accusé (\S+)$/, (m, a, b, c) => 'Ballot box ' + a + ' · ' + tx(b) + ' · receipt ' + c],
  [/^(\d+) \/ (\d+) parts requises$/, '$1 / $2 shares required'],
  [/^Bascule automatique en (\d+) s · aucune perte de données · bureaux de vote informés$/, 'Automatic failover in $1 s · no data lost · polling stations informed'],
  [/^(.*) · (\d+) votants test · résultats conformes$/, (m, a, n) => tx(a) + ' · ' + n + ' test voters · results as expected'],
  [/^Import contrôlé de la liste électorale v(\d+)$/, 'Checked import of electoral roll v$1'],
  [/^Import de la liste électorale v(\d+)$/, 'Electoral roll import v$1'],
  [/^([\d   ]+) lignes · (\d+) anomalie\(s\) · empreinte (\S+)$/, '$1 rows · $2 issue(s) · fingerprint $3'],
  [/^([\d   ]+) lignes · empreinte (\S+)$/, '$1 rows · fingerprint $2'],
  [/^([\d   ]+) lignes · (\d+) rectifications après réclamations$/, '$1 rows · $2 corrections after claims'],
  [/^Retour de (\d+) membres$/, '$1 members returned'],
  [/^Départ de (\d+) membres$/, '$1 members left'],
  [/^(\d+) détenteurs convoqués \(courriel et SMS\)$/, '$1 key holders invited (email and SMS)'],
  [/^Suspension de l’urne (.+) \(les autres urnes restent ouvertes\)$/, (m, u) => 'Ballot box ' + tx(u) + ' suspended (other boxes stay open)'],
  [/^Suspension du scrutin : (.*)$/, (m, r) => 'Election suspended: ' + tx(r)],
  [/^Alerte : (.*)$/, (m, r) => 'Alert: ' + tx(r)],
  [/^Anomalie détectée : (.*)$/, (m, r) => 'Anomaly detected: ' + tx(r)],
  [/^Ouverture du vote( \(second tour\))?$/, (m, r2) => 'Vote opened' + (r2 ? ' (second round)' : '')],
  [/^(\d+) questions? adoptées? sur (\d+)$/, '$1 of $2 questions adopted'],
  [/^(\d+) sièges répartis : (.*)$/, '$1 seats allocated: $2'],
  [/^Aucun candidat n’obtient la majorité absolue : (\S+) tour( à la majorité relative)?$/, (m, o, rel) => 'No absolute majority: ' + (ORD[o] || o) + ' round' + (rel ? ' by relative majority' : '')],
  [/^(.+) est élu·e au (\S+) tour \(majorité (absolue|relative)\)(.*)$/, (m, n, o, k, rest) => tx(n) + ' is elected in the ' + (ORD[o] || o) + ' round (' + (k === 'absolue' ? 'absolute' : 'relative') + ' majority)' + rest.replace(' · égalité de voix : élu·e au bénéfice de l’âge', ' · tie: elected as the oldest candidate')],
  [/^(.+) est élu·e \(majorité relative, scrutin à un tour\)$/, '$1 is elected (relative majority, single round)'],
  [/^(.+) sont désigné·e·s$/, (m, n) => n.replace(/ et ([^,]+)$/, ' and $1') + ' are appointed'],
  [/^(.+) est désigné·e$/, '$1 is appointed'],
  [/^Priorité n° 1 : (.*)$/, 'Top priority: $1'],
  [/^Consultation non décisionnaire : « (.*) » arrive en tête$/, (m, x) => 'Non-binding poll: “' + tx(x) + '” comes first'],
  [/^Candidat·e ([ABC]) \(fictif\)$/, 'Candidate $1 (fictitious)'],
  [/^Report du point (\S+) faute de quorum$/, 'Item $1 postponed (no quorum)'],
  [/^(\d+) échecs consécutifs sur l’accès de la CME · accès bloqué (\d+) min · organisateur et administrateur alertés$/, '$1 consecutive failures on CME sign-in · locked for $2 min · organiser and administrator alerted'],
  [/^Seuil de blocage : (\d+)$/, 'Lockout threshold: $1'],
  [/^Durée du blocage \(min\) : (\d+)$/, 'Lockout duration (min): $1'],
  [/^(Suspension|Reprise|Clôture) du scrutin « (.*) »$/, (m, k, x) => ({ Suspension: 'Suspension', Reprise: 'Resumption', Clôture: 'Closing' }[k]) + ' of election “' + tx(x) + '”'],
  [/^Proclamation des résultats « (.*) »$/, (m, x) => 'Declaration of results “' + tx(x) + '”'],
  [/^(Suspension|Reprise) de l’urne « (.*) »$/, (m, k, x) => (k === 'Suspension' ? 'Suspension' : 'Resumption') + ' of ballot box “' + tx(x) + '”'],
  [/^(.+) · ([\d   ]+) lignes$/, (m, a, n) => tx(a) + ' · ' + n + ' rows'],
  [/^Catégorie ([ABC])$/, 'Category $1'],
];

// Segments remplacés à l'intérieur d'un texte (du plus long au plus court)
const SEG = [
  ['Alerte : tentatives répétées (force brute)', 'Alert: repeated attempts (brute force)'],
  ['Alerte : connexion depuis une localisation inhabituelle', 'Alert: sign-in from an unusual location'],
  ['Déverrouillage d’un compte électeur après vérification d’identité', 'Voter account unlocked after identity check'],
  ['Émargement enregistré', 'Voter roll signed'],
  ['Fin de la période de vote (simulation de démonstration)', 'End of voting period (demo simulation)'],
  ['Accès électeurs fermé · en attente de clôture par le bureau', 'Voter access closed · awaiting closing by the polling station'],
  ['Scellement des urnes et des listes d’émargement après clôture', 'Ballot boxes and voter rolls sealed after closing'],
  ['Scellement des urnes et des listes d’émargement', 'Ballot boxes and voter rolls sealed'],
  ['Présentation d’une part de clé (déchiffrement partiel local)', 'Key share presented (local partial decryption)'],
  ['Scellement des résultats et des preuves de déchiffrement', 'Results and decryption proofs sealed'],
  ['Dépouillement réalisé (déchiffrement à seuil du total agrégé)', 'Count completed (threshold decryption of the aggregate)'],
  ['Preuves de déchiffrement publiées', 'Decryption proofs published'],
  ['Scellement final et archivage', 'Final seal and archiving'],
  ['Conservation sous scellés 2 ans · purge automatique programmée', 'Kept under seal for 2 years · automatic purge scheduled'],
  ['Contrôle d’intégrité déclenché manuellement', 'Manual integrity check'],
  ['Contrôle d’intégrité automatique', 'Automatic integrity check'],
  ['Bulletins = émargements · scellés et journal intègres', 'Ballots = roll signatures · seals and log intact'],
  ['Bulletins = émargements sur les 6 urnes · scellés intègres', 'Ballots = roll signatures in all 6 boxes · seals intact'],
  ['Contrôle automatique (toutes les 5 minutes)', 'Automatic check (every 5 minutes)'],
  ['Réémission sécurisée des identifiants', 'Secure credential reissue'],
  ['anciens identifiants révoqués', 'old credentials revoked'],
  ['Création d’un scrutin (en attente de double validation)', 'Election created (awaiting dual approval)'],
  ['Test de bascule vers le dispositif de secours', 'Failover test to the backup system'],
  ['Test de bascule planifié (PRA)', 'Scheduled failover test (DRP)'],
  ['Test de bascule PRA (période pré-électorale, planifié)', 'DRP failover test (pre-election, scheduled)'],
  ['Bascule vers l’opérateur SMS secondaire (incident fournisseur)', 'Switched to the backup SMS provider (supplier incident)'],
  ['Vote test exécuté', 'Test vote run'],
  ['Vote test avec les organisations syndicales', 'Test vote with the unions'],
  ['Modification de la politique de sécurité', 'Security policy changed'],
  ['Dépôt sur la plateforme d’échange sécurisée', 'Upload to the secure exchange platform'],
  ['Import contrôlé d’un fichier', 'Checked file import'],
  ['Ouverture de la séance du directoire', 'Executive board meeting opened'],
  ['Ouverture de la séance', 'Meeting opened'],
  ['Clôture de la séance et génération du procès-verbal', 'Meeting closed and minutes generated'],
  ['Clôture de la séance', 'Meeting closed'],
  ['Procès-verbal généré automatiquement', 'Minutes generated automatically'],
  ['PV scellé et horodaté', 'Minutes sealed and timestamped'],
  ['Émargement à l’arrivée', 'Signed in on arrival'],
  ['Départ en cours de séance', 'Left during the meeting'],
  ['Impact immédiat sur le quorum', 'Quorum updated immediately'],
  ['Quorum recalculé en temps réel', 'Quorum recalculated live'],
  ['Modification du vote avant clôture', 'Vote changed before closing'],
  ['Vote enregistré (émargement horodaté)', 'Vote recorded (timestamped sign-off)'],
  ['Au titre d’une procuration · ', 'As proxy · '],
  ['Suspension du vote', 'Vote suspended'],
  ['Reprise du vote', 'Vote resumed'],
  ['Prolongation du vote', 'Vote extended'],
  ['Clôture du vote et proclamation', 'Vote closed and result announced'],
  ['Annulation du vote', 'Vote cancelled'],
  ['Le vote pourra être relancé', 'The vote can be restarted'],
  ['Scellement et horodatage qualifié du procès-verbal', 'Minutes sealed with a qualified timestamp'],
  ['Transmission du procès-verbal', 'Minutes sent'],
  ['Création de la séance', 'Meeting created'],
  ['Ajout d’un point à l’ordre du jour', 'Agenda item added'],
  ['Alerte acquittée', 'Alert acknowledged'],
  ['Paramètre de sécurité modifié', 'Security setting changed'],
  ['Annonce d’une maintenance programmée à tous les utilisateurs', 'Scheduled maintenance announced to all users'],
  ['Retrait de l’annonce de maintenance', 'Maintenance notice removed'],
  ['Convocation des détenteurs de parts de clé au dépouillement', 'Key holders invited to the count'],
  ['Personnalisation des portails mise à jour', 'Portal branding updated'],
  ['Action critique validée par deux membres habilités', 'Critical action approved by two authorised members'],
  ['procédure d’incident', 'incident procedure'],
  ['Création de l’opération électorale', 'Election created'],
  ['niveau de sécurité 3 (délibération CNIL n° 2026-045)', 'security level 3 (CNIL deliberation 2026-045)'],
  ['Paramétrage des 6 urnes validé', '6 ballot boxes configured and approved'],
  ['3 collèges × 2 instances (CSE, F3SCT) · clés distinctes par urne', '3 colleges × 2 bodies (CSE, F3SCT) · one key per box'],
  ['Dépôt des candidatures enregistré', 'Candidacies registered'],
  ['4 listes CSE, 4 listes F3SCT (3 en catégorie B) · professions de foi et logos', '4 CSE lists, 4 F3SCT lists (3 in category B) · manifestos and logos'],
  ['Tirage au sort public de l’ordre d’affichage des listes', 'Public draw of the list display order'],
  ['En présence des délégués de liste', 'In the presence of list delegates'],
  ['Liste électorale v3 définitive', 'Final electoral roll v3'],
  ['Envoi des identifiants par courrier postal', 'Identifiers sent by post'],
  ['plis remis au routeur', 'letters handed to the mailer'],
  ['Envoi des mots de passe (SMS ou courriel)', 'Passwords sent (SMS or email)'],
  ['Canal distinct de celui de l’identifiant', 'Different channel from the identifier'],
  ['Rapport d’expertise remis', 'Expert report delivered'],
  ['Solution conforme · aucune réserve bloquante', 'Solution compliant · no blocking reservations'],
  ['Ouverture de la période d’enrôlement (application d’authentification)', 'Enrolment opened (authenticator app)'],
  ['Niveau 3 · enrôlement préalable obligatoire', 'Level 3 · prior enrolment required'],
  ['Formation des membres du bureau de vote', 'Polling station members trained'],
  ['Feuille d’émargement de la formation archivée', 'Training attendance sheet archived'],
  ['Vote test en présence des organisations syndicales', 'Test vote with the unions present'],
  ['24 votants test · résultats conformes au jeu d’essai', '24 test voters · results match the test set'],
  ['Réinitialisation de l’environnement de test', 'Test environment reset'],
  ['Urnes de production vierges confirmées', 'Production boxes confirmed empty'],
  ['Cérémonie des clés : génération distribuée', 'Key ceremony: distributed generation'],
  ['5 détenteurs · seuil 3 · 6 clés publiques publiées', '5 holders · threshold 3 · 6 public keys published'],
  ['Scellement du système, des listes et des horaires', 'System, lists and schedule sealed'],
  ['Clôture de l’enrôlement', 'Enrolment closed'],
  ['96,4 % des électeurs enrôlés · les autres utiliseront l’assistance', '96.4% of voters enrolled · the rest will use support'],
  ['Contrôle de vacuité avant ouverture (6 urnes vides, 0 émargement)', 'Empty-box check before opening (6 empty boxes, 0 signatures)'],
  ['Contrôle de vacuité avant ouverture', 'Empty-box check before opening'],
  ['6 urnes vides · 0 émargement (CNIL objectif 1-10)', '6 empty boxes · 0 signatures (CNIL objective 1-10)'],
  ['Ouverture du scrutin', 'Voting opened'],
  ['Dispositif principal actif · dispositif de secours synchronisé', 'Primary system active · backup in sync'],
  ['Connexion hors UE bloquée · identifiant', 'Sign-in outside the EU blocked · identifier'],
  ['Réémission d’identifiants (3 demandes)', 'Credentials reissued (3 requests)'],
  ['Vérification d’identité · envoi par canaux séparés', 'Identity checked · sent through separate channels'],
  ['Relance automatique J+7 des non-votants', 'Automatic day-7 reminder to non-voters'],
  ['SMS et courriel · aucune donnée de vote', 'SMS and email · no voting data'],
  ['Élections CME 2026 · 7 urnes', 'CME 2026 elections · 7 boxes'],
  ['Élections professionnelles 2026', '2026 staff elections'],
  ['Scellement initial (système, listes, électeurs, horaires)', 'Initial seal (system, lists, voters, schedule)'],
  ['Scellement intermédiaire quotidien des urnes', 'Daily interim seal of the boxes'],
  ['Connexion hors Union européenne bloquée pour l’identifiant', 'Sign-in from outside the EU blocked for identifier'],
  ['L’électeur a été contacté.', 'The voter has been contacted.'],
  ['Réémission après vérification d’identité (perte du courrier). Anciens identifiants révoqués.', 'Reissued after identity check (letter lost). Old credentials revoked.'],
  ['Un même terminal a été utilisé pour 4 identifiants distincts en 10 minutes (Site des Tilleuls). Vérification en cours avec l’encadrement.', 'One device was used for 4 different identifiers within 10 minutes (Site des Tilleuls). Being checked with management.'],
  ['Identifiant par SMS + mot de passe par courriel', 'Identifier by SMS + password by email'],
  ['Identifiant par courriel + mot de passe par SMS', 'Identifier by email + password by SMS'],
  ['Agent catégorie', 'Staff category'],
  ['Lenteurs ponctuelles du serveur SMS (opérateur B)', 'Occasional SMS server slowdowns (provider B)'],
  ['Demande d’ajout d’un membre observateur', 'Request to add an observer'],
  ['Connexion depuis un pays hors Union européenne', 'Sign-in from a country outside the EU'],
  ['Tentative d’accès à la séance du conseil de surveillance bloquée ; membre contacté', 'Access attempt to the supervisory board meeting blocked; member contacted'],
  ['CME · séance plénière · 11 points à l’ordre du jour', 'CME · plenary meeting · 11 agenda items'],
  ['Envoi des convocations et des liens personnels', 'Invitations and personal links sent'],
  ['67 destinataires · documents joints (12)', '67 recipients · 12 documents attached'],
  ['membres présents', 'members present'],
  ['Session de test avant la première utilisation', 'Test session before first use'],
  ['Prise en main accompagnée par le titulaire · 3 votes d’essai (nominatif, secret, sondage)', 'Guided onboarding by the supplier · 3 trial votes (roll-call, secret, poll)'],
  ['Quorum atteint · émargement automatique à l’arrivée', 'Quorum reached · automatic sign-in on arrival'],
  ['Point 1 traité', 'Item 1 done'],
  ['Constat du quorum', 'Quorum confirmed'],
  ['(voix prépondérante du président)', '(chair’s casting vote)'],
  ['+ 4 assesseurs', '+ 4 assessors'],
  ['DRH (Paul Renaud)', 'HR (Paul Renaud)'],
  ['DQE scénario', 'DQE scenario'],
  ['CSE et F3SCT · 3 collèges × 2 instances · 6 urnes distinctes', 'CSE and F3SCT · 3 colleges × 2 bodies · 6 separate ballot boxes'],
  ['7 collèges · multi-sites · scrutin plurinominal majoritaire à deux tours', '7 colleges · multi-site · two-round plurality vote'],
  ['Vote test réalisé en présence des organisations syndicales (24 votants test)', 'Test vote held with the unions present (24 test voters)'],
  ['Scrutin de liste à un tour, représentation proportionnelle à la plus forte moyenne', 'Single-round list vote, proportional representation (highest average)'],
  ['Scrutin plurinominal majoritaire à deux tours (panachage autorisé dans la limite des sièges)', 'Two-round plurality vote (mixing allowed up to the number of seats)'],
  ['Scrutin de liste à un tour (jeu d’essai contrôlé)', 'Single-round list vote (controlled test set)'],
  ['Vote test · Élections professionnelles 2026', 'Test vote · 2026 staff elections'],
  ['Comité social d’établissement (vote test)', 'Social committee (test vote)'],
  ['Comité social d’établissement', 'Social committee (CSE)'],
  ['Formation spécialisée en matière de santé, de sécurité et de conditions de travail', 'Health, safety and working conditions committee (F3SCT)'],
  ['Commission médicale d’établissement', 'Medical committee (CME)'],
  [' [modifié]', ' [modified]'], [' (démo)', ' (demo)'],
  [' · second tour · ', ' · second round · '], [' électeurs', ' voters'],
  [' · second tour', ' · second round'], [' · deuxième tour', ' · second round'], [' · troisième tour', ' · third round'],
  [' · hybride (', ' · hybrid ('], [' · présentiel', ' · in person'], [' · distanciel (', ' · remote ('], [' · séance fictive', ' · fictitious meeting'],
  ['Catégorie ', 'Category '],
  ['Collège test', 'Test college'],
  ['Collège ', 'College '],
  ['Empreinte ', 'Fingerprint '],
  [' · empreinte ', ' · fingerprint '],
  [' · jeton ', ' · token '],
  [' · accusé ', ' · receipt '],
  ['Accusé ', 'Receipt '],
  ['Identifiant ', 'Identifier '],
  ['identifiant ', 'identifier '],
].sort((a, b) => b[0].length - a[0].length);

// Nombres au format anglais : 8 500 → 8,500 ; 96,4 % → 96.4%
const enNum = (x) => x.replace(/(\d)[\u00a0\u202f ](?=\d{3}\b)/g, '$1,').replace(/(\d),(\d+)[\u00a0\u202f ]?%/g, '$1.$2%');

export function tx(s) {
  if (curLang() !== 'en' || typeof s !== 'string' || !s) return s;
  if (EXACT[s]) return EXACT[s];
  for (const [re, to] of RX) if (re.test(s)) return enNum(s.replace(re, to));
  let out = s;
  for (const [a, b] of SEG) if (out.includes(a)) out = out.split(a).join(b);
  return enNum(out);
}

// Texte de proclamation d'un résultat de vote en séance
export const resultText = (r) => (!r ? '' : curLang() === 'en' ? r.textEn || tx(r.text) : r.text);
