import os, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
import json
from playwright.sync_api import sync_playwright
OUT = os.environ.get('SHOTS_DIR', str(ROOT / 'tests' / 'shots')) + '/'
os.makedirs(OUT, exist_ok=True)
URL = os.environ.get('DEMO_URL', (ROOT / 'dist' / 'index.html').as_uri())
errors = []
def shot(pg, n, full=True): pg.screenshot(path=OUT + 'fb_' + n + '.png', full_page=full)
def go(pg, h, t=600): pg.evaluate("h => { location.hash = h }", h); pg.wait_for_timeout(t)
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 1366, 'height': 900})
    pg = ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(('pageerror', str(e))))
    pg.on('console', lambda m: errors.append(('console', m.text)) if m.type == 'error' else None)
    pg.goto(URL + '#/distance/bureau'); pg.wait_for_timeout(500)
    shot(pg, '00_login')
    pg.click('text=Se connecter (démo)'); pg.wait_for_timeout(1900)
    shot(pg, '01_dashboard')
    go(pg, '/distance/bureau/alertes'); shot(pg, '02_alertes')
    go(pg, '/distance/bureau/emargement'); shot(pg, '03_emargement')
    go(pg, '/distance/bureau/controles'); pg.click('text=Déclencher un contrôle'); pg.wait_for_timeout(3600); shot(pg, '04_controles')
    go(pg, '/distance/bureau/scellement'); pg.click('text=Vérifier les scellés maintenant'); pg.wait_for_timeout(1500); shot(pg, '05_scellement')
    pg.click('text=Rejouer la cérémonie'); pg.wait_for_timeout(300); shot(pg, '06_ceremony0', False)
    pg.click('text=Étape suivante'); pg.wait_for_timeout(3800); shot(pg, '06_ceremony1', False)
    pg.click('text=Étape suivante'); pg.wait_for_timeout(300)
    for i in range(5): pg.click('text=Remettre la part >> nth=0'); pg.wait_for_timeout(100)
    shot(pg, '06_ceremony2', False)
    pg.click('text=Étape suivante'); pg.wait_for_timeout(300); pg.click('text=Étape suivante'); pg.wait_for_timeout(300); shot(pg, '06_ceremony4', False)
    pg.click('text=Terminer'); pg.wait_for_timeout(300)
    go(pg, '/distance/bureau/journal'); pg.click('text=Vérifier l’intégrité'); pg.wait_for_timeout(300); shot(pg, '07_journal_ok', False)
    pg.click('text=Simuler une altération'); pg.wait_for_timeout(200); pg.click('text=Vérifier l’intégrité'); pg.wait_for_timeout(300); shot(pg, '08_journal_ko', False)
    pg.click('text=Restaurer le journal'); pg.wait_for_timeout(200)
    go(pg, '/distance/bureau/depouillement'); shot(pg, '09_dep0')
    pg.click('text=Avancer à la fin de la période de vote'); pg.wait_for_timeout(400); shot(pg, '10_dep1')
    pg.click('button:has-text("Clôturer le scrutin")'); pg.wait_for_timeout(400); shot(pg, '11_dual', False)
    pg.click('.modal .choice >> nth=0'); pg.click('text=Signer en tant que second membre'); pg.wait_for_timeout(2000)
    shot(pg, '12_dep2')
    pg.click('text=Sceller les urnes et les émargements'); pg.wait_for_timeout(400); shot(pg, '13_dep3')
    for i in range(3):
        pg.click('button:has-text("Présenter sa part") >> nth=0'); pg.wait_for_timeout(300); pg.click('.modal button:has-text("Présenter")'); pg.wait_for_timeout(1500)
    shot(pg, '14_shares')
    pg.click('text=Lancer le dépouillement'); pg.wait_for_timeout(5200); shot(pg, '15_counted')
    go(pg, '/distance/bureau/resultats'); shot(pg, '16_res_global')
    pg.click('role=tab[name="Par urne (collège)"]'); pg.wait_for_timeout(300); shot(pg, '17_res_urne')
    pg.click('role=tab[name="Par bureau de vote virtuel"]'); pg.wait_for_timeout(300); shot(pg, '18_res_site')
    pg.click('role=tab[name="Procès-verbal"]'); pg.wait_for_timeout(300); shot(pg, '19_pv')
    go(pg, '/distance/bureau/depouillement'); pg.click('text=Proclamer les résultats'); pg.wait_for_timeout(300); pg.click('.modal .choice >> nth=1'); pg.click('text=Signer en tant que second membre'); pg.wait_for_timeout(2000); shot(pg, '20_published')
    go(pg, '/distance/bureau/incidents'); shot(pg, '21_incidents')
    # voter sees closed
    go(pg, '/distance/electeur'); shot(pg, '22_voter_closed')
    b.close()
print(json.dumps(errors, ensure_ascii=False, indent=1)[:4000])
